### ISSUE TITLE
Error with smcFunc in latest version

### ISSUE THREAD

**Issue by berianwilliams** [SimpleMachines/smf-mw-auth#12]
I've set up test instances of SMF 2.0.14 and MediaWiki 1.25.2, in order to try to get the bridge set up (using the same versions we're using in production).  However, I get the following error when I try to load the wiki to test:

> Notice: Undefined variable: smcFunc in /home/ags/html/test/w/extensions/Auth_SMF.php on line 1011 Fatal error: Function name must be a string in /home/ags/html/test/w/extensions/Auth_SMF.php on line 1011

This is using the latest commit (https://github.com/SimpleMachines/smf-mw-auth/commit/57d27f84940e5d4297e0291db6dad3df1e5d1f5d#diff-6ce162690b9b3a24a064ce0e609cc4a5) with no changes made to SMF or MW aside from setting up the bridge.

My LocalSettings.php is here: https://pastebin.com/Qcu14eNQ.  Any ideas why this might be happening?

**Comment by jdarwood007** [comment]
The referenced commit should resolve this.

**Comment by berianwilliams** [comment]
That error is now fixed, thanks!  Just so you're aware though, now I'm seeing:

> Warning: mysql_fetch_assoc() expects parameter 1 to be resource, object given in /home/USER/html/test/w/extensions/Auth_SMF.php on line 157

However, now the error's fixed, the bridge isn't working as intended.  I try logging in to SMF through the Log In button in MW, which succeeds, but my logged in user isn't detected on the MW side.
