### ISSUE TITLE
MW login not working

### ISSUE THREAD

**Issue by berianwilliams** [SimpleMachines/smf-mw-auth#13]
Using commit https://github.com/SimpleMachines/smf-mw-auth/commit/357df72cac92dc227bcfac8715a6f464c9f2407b I get following warning:

    Warning: mysql_fetch_assoc() expects parameter 1 to be resource, object given in /home/USER/html/test/w/extensions/Auth_SMF.php on line 157

Aside from this (or perhaps because of it?) the bridge isn't working as intended. I try logging in to SMF through the Log In button in MW, which succeeds, but my logged in user isn't detected on the MW side. Th e user I'm logging in with is a forum administrator.

**Comment by jdarwood007** [comment]
I made some commits which I think would resolve this.  I havent' had time to test it yet.  This was part of the work to add multi-database support to the Auth.

**Comment by berianwilliams** [comment]
> Fatal error: Call to undefined method Auth_SMF::query() in Auth_SMF.php on line 841

**Comment by jdarwood007** [comment]
Corrected that issue.
