### ISSUE TITLE
Errors in MW 1.31.1

### ISSUE THREAD

**Issue by berianwilliams** [SimpleMachines/smf-mw-auth#14]
I appreciate the plugin hasn't been updated in a while, but are you expecting it to work in newer versions of MediaWiki?  I'm running MW 1.31.1 and getting various errors.  I can provide xdebug stack traces if you need them to investigate.

**Comment by Vekseid** [comment]
I ended up writing my own extension for SMF and Elkarte, see here:

https://github.com/Vekseid/ForumSessionProvider

**Comment by jdarwood007** [comment]
This extension has been updated for 1.35 based on @Vekseid work.  It may function on 1.31 but wasn't tested.
