### ISSUE TITLE
People not being removed from Wiki groups

### ISSUE THREAD

**Issue by Nutbolt52** [SimpleMachines/smf-mw-auth#4]
I have got this running and I have it setup so that there's a SMF group named Mentors, and a wiki group named Editor. If they are added to the SMF Mentors group, they are then added to the wiki Editor group. However if I remove them from the SMF group, they are not being removed from the wiki group. I have given it plenty of time (hours) for any kind of caching to go, and no luck. 

Any ideas why people aren't being removed from the groups on wiki? Thanks

**Comment by jdarwood007** [comment]
Is this still an issue?  The Auth plugin does cache and delay updates.  It could take 30 minutes before you see a change.

**Comment by Nutbolt52** [comment]
Sorry it has been years since I stopped using this so I am not sure if it is still an issue.

**Comment by jdarwood007** [comment]
Ok, closing then.
