### ISSUE TITLE
can't assign bureaucrat role anyhow

### ISSUE THREAD

**Issue by snoer** [SimpleMachines/smf-mw-auth#5]
since I can't login with the mediaWiki's admin account the only possibility to grant another user bureaucrat rights seems to do so via LocalSettings.php

I removed the Admin user via phpmyadmin from the wiki_users and created the account again after adding the following to my LocalSettings.php. 

$wgSMFSpecialGroups = array(
        1 => 'bureaucrat'
);

this doesn't seem to have any effect.
I run SMF 2.0.4, MediaWiki 1.21

**Comment by jdarwood007** [comment]
This is how MW handles the bureaucrat role.  It could possibly change in the newer auth plugins.
