### ISSUE TITLE
Cannot login?

### ISSUE THREAD

**Issue by sirexile** [SimpleMachines/smf-mw-auth#7]
I can't get the bridge to work with the latest version of mediawiki and smf (2.0.9). It's fully installed, hooked up to a subdomain wiki.domain.com and forums is forums.domain.com (same domain)

When on the wiki i click login, takes me to smf login, logs in fine however mediawiki does not reflect this login (It stays on the forum.)

My plugins:
1.   Split Forum Mod   1.10   [ Uninstall ]
2.   RSS Feed Poster   4.1   [ Uninstall ]
3.   Menu Editor Lite   1.0.5   [ Uninstall ]
4.   @mention members   1.1.2   [ Uninstall ]
5.   Default Avatar   2.3   [ Uninstall ]
6.   Spoiler Tag   0.7.2a   [ Uninstall ]
7.   Gamer IDs   1.4   [ Uninstall ]
8.   Ultimate Profile   0.9.1   [ Uninstall ]
9.   Download bbcode 2.0   2.0   [ Uninstall ]
10.   PartyMembers   1.0   [ Uninstall ]
11.   URL Popup   1.0.2   [ Uninstall ]
12.   VigLink   1.3   [ Uninstall ]
13.   Battle   1.14   [ Uninstall ]
14.   Member Color Link   3.1   [ Uninstall ]
15.   SimplePortal   2.3.5   [ Uninstall ]
16.   Tidy Child Boards   1.4.1   [ Uninstall ]
17.   Member Awards   3.0   [ Uninstall ]
18.   Relative Dates   1.3   [ Uninstall ]
19.   AJAX Recent Topics   1.1   [ Uninstall ]
20.   Tabbed smileys   0.3.99e   [ Uninstall ]
21.   BBC User Info   2.0   [ Uninstall ]
22.   Tagging System   3.0   [ Uninstall ]
23.   Stop Spammer   2.3.9   [ Uninstall ]
24.   reCAPTCHA for SMF   0.9.8a   [ Uninstall ]
25.   Board Icons   1.0   [ Uninstall ]
26.   SMF Social Groups   2.4.5   [ Uninstall ]
27.   Avatar On Board RC2   2.1   [ Uninstall ]
28.   SMF 2.0.8 Update   1.0   [ Uninstall ]
29.   SMF 2.0.7 Update   1.0   [ Uninstall ]
30.   SMF 1.1.19 / 2.0.6 Update   1.0   [ Uninstall ]
    Modify message

**Comment by jdarwood007** [comment]
@sirexile Is this still occurring?
