### ISSUE TITLE
500 Internal Server Error with v1.24.0

### ISSUE THREAD

**Issue by Tokzu** [SimpleMachines/smf-mw-auth#8]
Hello,

This morning I upgraded my MediaWiki to 1.24.0 but I received an 500 Internal Server Error and in my error log is is displayed:

20141127T130128: wiki.kaero-webs.com/index.php 
PHP Fatal error:  Cannot access protected property User::$mOptionOverrides in /wiki/extensions/Auth_SMF.php on line 1050

Maybe is because the new version, by the way in 1.23 I don't have this problem.

**Comment by sagnitude** [comment]
Modify wiki/includes/User.php:

search for `protected $mOptionOverrides;`

replace it with `public $mOptionOverrides;`

this shall fix it.

**Comment by jdarwood007** [comment]
I wonder what they changed that caused this.  

https://git.wikimedia.org/blob/mediawiki%2Fcore/HEAD/includes%2FUser.php
Looking at their git repo, the User class hasn't changed from what I see to cause that.

**Comment by sagnitude** [comment]
The change was introduced in this commit:

https://git.wikimedia.org/commitdiff/mediawiki%2Fcore/2daa1fab7a200ac2045e1e03e17a19fea1792afe

It seems they were trying to drop support for PHP 4.4 which doesn't support the keyword 'protected'.

**Comment by jdarwood007** [comment]
@sagnitude Is this still an issue?

**Comment by jdarwood007** [comment]
Closing this as we are targeting 1.27 at this point and will support future releases.  1.24 is EOL for MediaWiki
