### ISSUE TITLE
User not being logged in proper

### ISSUE THREAD

**Issue by Nutbolt52** [SimpleMachines/smf-mw-auth#9]
Weirdly we have some users who now aren't being logged into the wiki properly. I am running the latest of this plugin/extension and of SMF. They have the same permissions as others who can access the wiki fine. The user gets partly logged in, but gets the following error and can't access any private pages on the wiki (i.e. anything apart from the homepage): 

http://tinypic.com/view.php?pic=r73t6w&s=8#.VLp0kdWsXV8 

Any help would be appreciated, I cannot work out what the problem is or where to begin troubleshooting it (cleared all his cookies etc...)

**Comment by jdarwood007** [comment]
@Nutbolt52 Is this still an issue?

**Comment by Nutbolt52** [comment]
Sorry it has been well over a year since I stopped using this so I am not sure if it is still an issue.
